version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "4000:3000"
    environment:
      PGRST_DB_URI: postgres://test:test@10.0.2.180:5432/Application
      PGRST_JWT_SECRET: "qkkejklwvblkrenbklenbklernklvbenrklvnre"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "Application"