version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "4000:3000"
    environment:
      PGRST_DB_URI: postgres://test:test@10.0.2.180:5432/Application
      PGRST_JWT_SECRET: "qkkejklwvblkrenbklenbklernklvbenrklvnre"
